### ISSUE TITLE
doesn't `npm install` all required files

### ISSUE THREAD

**Issue by mateodelnorte** [phihag/pdfform.js#5]
doing the following
1. `npm i --save pdfform.js`
2. `node`
3. `require('pdfform.js')`
gets the following results:
```
> require('pdfform.js')
Error: Cannot find module './libs/pako.min.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mateodelnorte/development/consensys/gridplus/token-contract-filler/node_modules/pdfform.js/pdfform.js:11:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```
why not just `npm install --save pako` and require it directly, instead of requiring this custom step? https://github.com/phihag/pdfform.js/blob/d933810436619d733a25e6b7f6dae48f62649b4c/pdfform.js#L11

**Comment by phihag** [comment]
Sorry for the delay. With pdfform.js 1.0.6 and newer, `npm i` is sufficient. Thank you for the report!
